eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/



server:
  port: 8092
spring:
  application:
    name: service-feign
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
      prefix: classpath:/templates/
      suffix: .html
  data:
    solr:
      host: http://localhost:8010/solr

